USE
GO
CREATE TABLE OpenBudget
(
FY INT
FUND INT
Fund_Name VARCHAR(40),
AREA	
Area_Name VARCHAR(40),
1ST_SUBTOTAL INT
2ND_SUBTOTAL INT
3RD_SUBTOTAL INT	
ACCOUNT	VARCHAR(40),
TITLE VARCHAR(40),
BUDGET INT
PERIOD_EXPENDITURES	INT
ENCUMBRANCES_OUTSTANDING INT
YEAR_TO_DATE_EXP INT
AVAILABLE BALANCE INT
YTD_BUD INT
)